openapi: 3.0.1
info:
  title: DigimonTCG REST API
  description: They are the champions
  version: 1.0.0
servers:
- url: /api/v1
paths:
  /sets:
    get:
      summary: Get available sets
      responses:
        "200":
          description: JSON array of sets
          content:
            application/json:
              schema: 
                type: object
                properties:
                  sets:
                    type: array
                    items: 
                      $ref: "#/components/schemas/Set"
  /cards:
    get:
      summary: Get available cards
      parameters:
        - name: name
          description: Search by card name
          in: query
          schema:
            type: string
        - name: number
          description: Search by card number
          in: query
          schema:
            type: string
        - name: set
          description: Search by card set
          in: query
          schema:
            type: string
        - name: rarity
          description: Search by card rarity
          in: query
          schema:
            type: string
        - name: sort
          description: Sort results by a specific field
          in: query
          schema:
            type: string
            enum:
              - name
              - -name
              - number
              - -number
            default: number
        - name: page
          description: Select which page of results to view
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          description: Select the size of each page
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        "200":
          description: JSON array of cards
          content:
            application/json:
              schema: 
                type: object
                properties:
                  cards:
                    type: array
                    items: 
                      $ref: "#/components/schemas/Card"
components:
  schemas:
    Set:
      type: object
      properties:
        number:
          type: string
        name:
          type: string
        releaseDate:
          type: string
          format: date
    Card:
      type: object
      properties:
        set:
          type: string
        name:
          type: string
        nameIncludes:
          type: array
          items:
            type: string
        nameTreatedAs:
          type: array
          items:
            type: string
        number:
          type: string
        rarity:
          type: string
        type:
          type: string
        colors:
          type: array
          items:
            type: string
        images:
          type: array
          items:
            type: string
            format: uri
        form:
          type: string
        attributes:
          type: array
          items:
            type: string
        types:
          type: array
          items:
            type: string
        effects:
          type: array
          items:
            type: string
        inheritedEffects:
          type: array
          items:
            type: string
        securityEffects:
          type: array
          items:
            type: string
        cost:
          type: integer
        playCost:
          type: integer
        dp:
          type: integer
        level:
          type: integer
        abilities:
          type: array
          items:
            type: string
        digivolutionRequirements:
          type: array
          items:
            $ref: "#/components/schemas/DigivolveCost"
        dnaDigivolutionRequirements:
          type: array
          items:
            $ref: "#/components/schemas/DNADigivolveCost"
        digiXrosRequirements:
          type: array
          items:
            $ref: "#/components/schemas/DigiXrosCost"
    DigivolveCost:
      type: object
      properties:
        cost:
          type: integer
        from:
          $ref: "#/components/schemas/DigivolveFrom"
    DNADigivolveCost:
      type: object
      properties:
        cost:
          type: integer
        from:
          type: array
          items:
            $ref: "#/components/schemas/DigivolveFrom"
    DigivolveFrom:
      type: object
      properties:
        color:
          type: string
        level:
          type: integer
        name:
          type: string
        sources:
          type: array
          items:
            type: string
        tamer:
          type: boolean
    DigiXrosCost:
      type: object
      properties:
        cost:
          type: integer
        fromNames:
          type: array
          items:
            type: string
        fromTraits:
          type: array
          items:
            $ref: "#/components/schemas/DigiXrosFromTraits"
    DigiXrosFromTraits:
      type: object
      properties:
        count:
          type: integer
        traits:
          type: array
          items:
            type: string
        traitsContain:
          type: array
          items:
            type: string
        uniqueNames:
          type: boolean
        uniqueNumbers:
          type: boolean
