before:
  hooks:
    - go mod tidy

builds:
  - main: main.go
    binary: digimontcg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - package_name: digimontcg
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://github.com/theandrew168/digimontcg
    maintainer: Andrew Dailey <andrew@shallowbrooksoftware.com>
    description: They are the champions
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: script/digimontcg.service
        dst: /lib/systemd/system/digimontcg.service
        type: config
    scripts:
      postinstall: script/postinstall.sh
      preremove: script/preremove.sh
      postremove: script/postremove.sh

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
