# Generated by Django 4.1.4 on 2022-12-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.TextField(unique=True)),
                ("name", models.TextField()),
                ("release_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.TextField(unique=True)),
                ("name", models.TextField()),
                (
                    "rarity",
                    models.IntegerField(
                        choices=[
                            (0, "Common"),
                            (1, "Uncommon"),
                            (2, "Rare"),
                            (3, "Super Rare"),
                            (4, "Secret Rare"),
                            (5, "Promo"),
                        ]
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Digi-Egg"),
                            (1, "Digimon"),
                            (2, "Tamer"),
                            (3, "Option"),
                        ]
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        choices=[
                            (0, "Red"),
                            (1, "Blue"),
                            (2, "Yellow"),
                            (3, "Green"),
                            (4, "Black"),
                            (5, "Purple"),
                            (6, "White"),
                        ]
                    ),
                ),
                ("images", models.JSONField(default=list)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="digimontcg.set"
                    ),
                ),
            ],
        ),
    ]
