# Generated by Django 4.1.4 on 2023-01-13 05:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.TextField(unique=True)),
                ("name", models.TextField()),
                ("release_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "name_includes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "name_treated_as",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("number", models.TextField(unique=True)),
                ("rarity", models.TextField()),
                ("type", models.TextField()),
                (
                    "colors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), size=None
                    ),
                ),
                ("form", models.TextField(null=True)),
                (
                    "attributes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("effects", models.JSONField()),
                ("inherited_effects", models.JSONField()),
                ("security_effects", models.JSONField()),
                ("cost", models.IntegerField(null=True)),
                ("play_cost", models.IntegerField(null=True)),
                ("dp", models.IntegerField(null=True)),
                ("level", models.IntegerField(null=True)),
                (
                    "abilities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("digivolution_requirements", models.JSONField()),
                ("dna_digivolution_requirements", models.JSONField()),
                ("digixros_requirements", models.JSONField()),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="digimontcg.set"
                    ),
                ),
            ],
        ),
    ]
